# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6837d97fbfe34710cbc49d32ad6647f76c27e727af34272e6aba4fb4e01a6ec2aa143d3c77341b05fd7cb3055e04445bd454654777812c675662cc1e74be9063

test:
  secret_key_base: 15fce310cbf6613015195e4e7100a2cd152cab58146b50a5c4eaa69a6567c562962887aadd26701343e7a1b68d861f3b6e50f799f1505269ff49956340aa7b35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
